# Generated by Django 5.2.7 on 2026-08-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerleads', '0005_lead_call_outcome_lead_call_outcome_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='recording_url',
            field=models.URLField(blank=True),
        ),
    ]
