# Generated by Django 5.2.7 on 2026-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerleads', '0004_alter_lead_options_lead_additional_field_14_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='call_outcome',
            field=models.CharField(blank=True, choices=[('success', 'Confirmed'), ('unreachable', 'Unreachable'), ('failed', 'Failed'), ('not_answered', 'Not Answered')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='call_outcome_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('negotiation', 'In Negotiation'), ('closed', 'Closed/Won'), ('lost', 'Closed/Lost'), ('confirmed', 'Confirmed'), ('unreachable', 'Unreachable'), ('failed', 'Failed'), ('not_answered', 'Not Answered')], default='new', max_length=20),
        ),
    ]
